### PR TITLE
Modified Technique and Sub Technique Module

### PR DESCRIPTION
**Pull request by cs-rohit-khune**
[Mantis #0770019 ](https://mantis.fortinet.com/bug_view_page.php?bug_id=0770019) - Update the fields that need to be displayed in Alert SVT to 'default grid column'

### CODE REVIEW

**Comment by cs-rohit-khune** [comment]
Issue: In Alert SVT, the correlated Techniques or Subtechniques are not displaying any column
Resolution: 
[Resolution.docx](https://github.com/fortinet-fortisoar/solution-pack-mitre-attack/files/7865492/Resolution.docx)
Please refer to attached

**Comment by cs-tan-kucukoglu** [comment]
Looks good to me. Thanks Rohit.

**Comment by cs-suyog-jinturkar** [comment]
1. I see field names has changed. Any PB impact due to this?
2. What all unit testing was carried out to test this change?

**Comment by cs-rohit-khune** [comment]
1. I see field names has changed. Any PB impact due to this?
    > Yes, The name impacts playbook that links Technique to Alert record. However, Under Mantis #0773714 we will removing these playbooks. The relavant changes has been made in PBs and will be uploaded in MITRE ATT&CK Threat Hunting - 1.0.0 SP
2. What all unit testing was carried out to test this change
Please refer  [Mantis ID - 0770019 Unit Test Case Document.docx](https://github.com/fortinet-fortisoar/solution-pack-mitre-attack/files/7891111/Mantis.ID.-.0770019.Unit.Test.Case.Document.docx)

**Review by cs-tushar-kanade — APPROVED** [review]

**Pull request merged**
